package hu.logcontrol.wasteprogram.enums;

public enum ActivityEnums {

    MAIN_ACTIVITY,
    MODES_ACTIVITY_ONE,
    MODES_ACTIVITY_TWO,
    MODES_ACTIVITY_THREE,
    RAW_MATERIAL_CREATION_ACTIVITY,
    RAW_MATERIAL_TYPEMASS_CREATION_ACTIVITY,
    RECYCLED_MATERIAL_TYPEMASS_CREATION_ACTIVITY,
    FOLDERPICKER_ACTIVITY
}
