package hu.logcontrol.wasteprogram.enums;

public enum EditButtonEnums {
    ADD_BUTTON_ENABLED,
    ADD_BUTTON_DISABLED,
    DELETE_BUTTON_ENABLED,
    DELETE_BUTTON_DISABLED,
    SAVE_BUTTON_ENABLED,
    SAVE_BUTTON_DISABLED,
    ENTER_BUTTON_ENABLED,
    ENTER_BUTTON_DISABLED
}
